import 'swiper/css'
import 'swiper/css/pagination'
import 'swiper/css/navigation'
import 'animate.css'
import './globals.css'
import type { Metadata } from 'next'
import Header from './components/Header'
import Footer from './components/Footer'
import { Inter } from 'next/font/google'
import Container from './components/Containers/Container'
import { AosProvider } from './components/Providers/AosProvider'
import ReactQueryProvider from './components/Providers/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ReactQueryProvider>
          <AosProvider>
            <Container>
              <Header />
              {children}
              <Footer />
            </Container>
          </AosProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
